-- ============================================================
-- AppointmentIQ — Supabase Database Schema
-- Run this in the Supabase SQL Editor (https://app.supabase.com)
-- ============================================================

-- Drop table if you need a clean slate during development:
-- DROP TABLE IF EXISTS appointments;

CREATE TABLE IF NOT EXISTS appointments (
  -- Primary key: UUID generated by PostgreSQL (not the app)
  -- UUID is better than auto-increment for distributed systems
  -- and prevents enumeration attacks (ids aren't sequential)
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Customer information
  customer_name       TEXT NOT NULL
                        CHECK (char_length(trim(customer_name)) BETWEEN 2 AND 100),

  -- Phone in E.164 format: +[country code][number], e.g. +12345678900
  -- The CHECK constraint mirrors the backend express-validator rule
  phone_number        TEXT NOT NULL
                        CHECK (phone_number ~ '^\+[1-9]\d{6,14}$'),

  -- Stored as TIMESTAMPTZ (with timezone) so Supabase preserves
  -- the exact UTC moment regardless of server timezone
  appointment_time    TIMESTAMPTZ NOT NULL,

  -- Optional free-text notes
  notes               TEXT CHECK (char_length(notes) <= 500),

  -- Twilio tracking columns
  -- twilio_sid: the Message SID from the confirmation SMS
  -- Used for auditing and support ("can you resend my confirmation?")
  twilio_sid          TEXT,

  -- reminder_sent: the authoritative flag for the scheduler
  -- DEFAULT FALSE — every new appointment needs a reminder
  reminder_sent       BOOLEAN NOT NULL DEFAULT FALSE,

  -- When the reminder was actually sent (UTC)
  reminder_sent_at    TIMESTAMPTZ,

  -- The Twilio SID for the reminder SMS (for auditing)
  reminder_twilio_sid TEXT,

  -- Audit timestamps — auto-set by PostgreSQL
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ── Auto-update `updated_at` trigger ────────────────────────────────────────
-- PostgreSQL doesn't update updated_at automatically — we need a trigger.
-- This fires BEFORE any UPDATE and sets updated_at to the current timestamp.

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Drop trigger first to allow re-running this script safely
DROP TRIGGER IF EXISTS appointments_set_updated_at ON appointments;

CREATE TRIGGER appointments_set_updated_at
  BEFORE UPDATE ON appointments
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at_column();

-- ── Indexes ──────────────────────────────────────────────────────────────────

-- Index for the scheduler's query: reminder_sent + appointment_time
-- The WHERE clause makes this a partial index — only indexes FALSE rows,
-- which is a small fraction of the table as appointments get reminded.
-- This makes the scheduler query very fast even at scale.
CREATE INDEX IF NOT EXISTS idx_appointments_reminder_pending
  ON appointments (appointment_time ASC)
  WHERE reminder_sent = FALSE;

-- Index for the dashboard's ORDER BY appointment_time
CREATE INDEX IF NOT EXISTS idx_appointments_time_asc
  ON appointments (appointment_time ASC);

-- ── Row Level Security ────────────────────────────────────────────────────────
-- Enable RLS to block direct anon/browser access to this table.
-- The backend uses the service role key, which bypasses RLS entirely.
-- This means: only our trusted backend can read/write this table.

ALTER TABLE appointments ENABLE ROW LEVEL SECURITY;

-- No RLS policies needed since:
-- 1. Backend uses service role key (bypasses RLS)
-- 2. We don't want any anon/authenticated user to access this table directly

-- ── Verify setup ─────────────────────────────────────────────────────────────
-- Run this to confirm the table and indexes were created:

SELECT
  column_name,
  data_type,
  is_nullable,
  column_default
FROM information_schema.columns
WHERE table_name = 'appointments'
ORDER BY ordinal_position;
